name: macOS CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  rust:
    name: macOS
    uses: ./.github/workflows/rust-ci-reusable.yml
    with:
      runner: macos-latest
